# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

steps:
    - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
      displayName: 'Run CredScan'
      inputs:
        debugMode: false