# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: "windows-latest"

variables:
  BRANCH: 'weeklyOpenApiDocsDownload'
  GitUserEmail: 'GraphTooling@service.microsoft.com'
  GitUserName: 'Microsoft Graph DevX Tooling'
  BaseBranch: 'dev'

schedules:
    - cron: "0 0 * * WED" # Run Every Wednesday
      displayName: "Weekly OpenApiDocs Download and PR"
      branches: 
        include:
        - dev
      always: true

stages:
- stage: DownloadOpenApiDocs
  displayName: 'Download Open Api Docs from DevX API'
  jobs:
  - job: DownloadOpenAPiDocs
    steps:
    - template: ./download-openapidocs-template.yml
      parameters:
        GitUserEmail: $(GitUserEmail)
        GitUserName: $(GitUserName)
        BaseBranch: $(BaseBranch)