# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Generates a release build artifact (nuget) for beta roll-up module.
parameters:
  - name: ROLLUP_MODULE_PATH
    displayName: 'Module Path'
    type: string
    default: 'src/Beta/Graph/Graph'
  - name: ROLLUP_MODULE_NAME
    displayName: 'Module Name'
    type: string
    default: 'Graph'
  - name: Api_Key
    displayName: 'Api Key'
    type: string
  - name: GRAPH_VERSION
    displayName: 'Graph Version'
    type: string
    default: 'beta'
  - name: MODULE_PREFIX
    displayName: 'Module Prefix'
    type: string
    default: 'Microsoft.Graph'
  - name: EnableSigning
    displayName: 'Enable Signing'
    type: boolean
    default: false
jobs:
- job: MSGraphPSSDKGeneration
  displayName: MS Graph PS SDK Roll-Up Generation
  timeoutInMinutes: 300
  pool:
    vmImage: 'windows-latest'
  
  steps:
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
    displayName: 'Run CredScan'
    inputs:
      debugMode: false
  
  - task: NuGetToolInstaller@1
    displayName: 'Install Nuget'
  
  - task: PowerShell@2
    displayName: 'Generate and Build Roll-Up Module'
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/tools/GenerateRollUpModule.ps1'
      arguments: '-RepositoryApiKey $(Api_Key) -ArtifactsLocation $(Build.ArtifactStagingDirectory)/$(GRAPH_VERSION)/'
      pwsh: true
  
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP CodeSigning (Graph Roll-Up Module)'
    enabled: false
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet'
      FolderPath: $(ROLLUP_MODULE_PATH)
      Pattern: '$(MODULE_PREFIX).psm1, $(MODULE_PREFIX).*.format.ps1xml, *.ps1'
      signConfigType: inlineSignParams
      inlineOperation: |
       [
           {
               "keyCode": "CP-230012",
               "operationSetCode": "SigntoolSign",
               "parameters": [
                   {
                       "parameterName": "OpusName",
                       "parameterValue": "Microsoft"
                   },
                   {
                       "parameterName": "OpusInfo",
                       "parameterValue": "http://www.microsoft.com"
                   },
                   {
                       "parameterName": "FileDigest",
                       "parameterValue": "/fd \"SHA256\""
                   },
                   {
                       "parameterName": "PageHash",
                       "parameterValue": "/NPH"
                   },
                   {
                       "parameterName": "TimeStamp",
                       "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                   }
               ],
               "toolName": "sign",
               "toolVersion": "1.0"
           },
           {
               "keyCode": "CP-230012",
               "operationSetCode": "SigntoolVerify",
               "parameters": [],
               "toolName": "sign",
               "toolVersion": "1.0"
           }
       ]
      SessionTimeout: 20
  
  - task: NuGetCommand@2
    displayName: 'Pack Roll-Up Module'
    inputs:
      command: 'pack'
      Configuration: Release
      packagesToPack: '$(System.DefaultWorkingDirectory)/$(ROLLUP_MODULE_PATH)/$(MODULE_PREFIX).nuspec'
      packDestination: '$(Build.ArtifactStagingDirectory)/$(GRAPH_VERSION)/'
      versioningScheme: 'off'
  
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
    displayName: 'ESRP NuGet CodeSigning'
    enabled: false
    inputs:
      ConnectedServiceName: 'microsoftgraph ESRP CodeSign DLL and NuGet'
      FolderPath: '$(Build.ArtifactStagingDirectory)/$(GRAPH_VERSION)/'
      Pattern: 'Microsoft.Graph*.nupkg'
      signConfigType: inlineSignParams
      inlineOperation: |
            [
                {
                    "keyCode": "CP-401405",
                    "operationSetCode": "NuGetSign",
                    "parameters": [ ],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                },
                {
                    "keyCode": "CP-401405",
                    "operationSetCode": "NuGetVerify",
                    "parameters": [ ],
                    "toolName": "sign",
                    "toolVersion": "1.0"
                }
            ]
      SessionTimeout: 20

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact Microsoft.Graph.nupkg'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(GRAPH_VERSION)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: YodLabs.O365PostMessage.O365PostMessageBuild.O365PostMessageBuild@0
    displayName: 'Graph Client Tooling pipeline fail notification'
    inputs:
      addressType: serviceEndpoint
      serviceEndpointName: 'microsoftgraph pipeline status'
      title: '$(Build.DefinitionName) failure notification'
      text: 'This pipeline has failed. View the build details for further information. This is a blocking failure. '
    condition: and(failed(), ne(variables['Build.Reason'], 'Manual'))
    enabled: true