# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: 'Integrated Pipeline'
variables:
- name: BRANCH
  value: 'weeklyOpenApiDocsDownload'
- name: GitUserEmail
  value: 'GraphTooling@service.microsoft.com'
- name: GitUserName
  value: 'Microsoft Graph DevX Tooling'
- name: BaseBranch
  value : 'dev'
- name: AUTH_MODULE_NAME
  value: 'Authentication'
- name: AUTH_MODULE_PATH
  value: 'src\Authentication\Authentication'
- name: AUTH_MODULE_DLL_PATTERN
  value: 'Microsoft.Graph.Authentication.dll'
- name: MODULE_DLL_PATTERN
  value: 'Microsoft.Graph.Authentication.dll'
- name: BETA_MODULE_PREFIX
  value: 'Microsoft.Graph'
- name: ROLLUP_MODULE_NAME
  value: 'Graph'
- name: ROLLUP_MODULE_PATH
  value: 'src/Graph/Graph'
- name: WORKLOAD_MODULE_PATH
  value: 'src'
- name: GRAPH_VERSION
  value: 'beta'
- name: Api_Key
  value: 'Api_Key'
- name: EnableSigning
  value: ${{false}}
  
pool:
    vmImage: 'windows-latest'
trigger:
    branches:
      include:
      - master
    paths:
      include:
        - src/*
        - config/ModulesMapping.jsonc
      exclude:
        - src/Authentication/*
resources:
  - repo: self

stages:
- stage: CredentialScanning
  displayName: 'Scan for Credentials in CodeBase'
  jobs:
  - job: CredentialScanning
    steps:
    - template: ./credential-scanning-template.yml

- stage: DownloadOpenApiDocs
  displayName: 'Download Open Api Docs from DevX API'
  jobs:
  - job: DownloadOpenAPiDocs
    steps:
    - template: ./download-openapidocs-template.yml
      parameters:
        GitUserEmail: $(GitUserEmail)
        GitUserName: $(GitUserName)
        BaseBranch: $(BaseBranch)

- stage: GenerateProfiles
  displayName: 'Generate Profiles'
  jobs:
  - job: GenerateProfiles
    steps:
    - template: ./generate-profiles-template.yml

- stage: GenerateAuthModule
  displayName: 'Generate Authentication Module (Microsoft.Graph.Authentication)'
  jobs:
  - template: ./generate-auth-module-template.yml
    parameters:
      Api_Key: $(Api_Key)
      AUTH_MODULE_NAME: $(AUTH_MODULE)
      AUTH_MODULE_PATH: $(AUTH_MODULE_PATH)
      AUTH_MODULE_DLL_PATTERN: $(AUTH_MODULE_DLL_PATTERN)
      EnableSigning: false

    
- stage: GenerateBetaModules
  displayName: 'Generate Beta Modules (Microsoft.Graph.*)'
  jobs:
  - template: ./generate-beta-modules-template.yml
    parameters:
      Api_Key: $(Api_Key)
      BETA_MODULE_PREFIX: $(BETA_MODULE_PREFIX)
      WORKLOAD_MODULE_PATH: $(WORKLOAD_MODULE_PATH)
      GRAPH_VERSION: $(GRAPH_VERSION)
      AUTH_MODULE_PATH: $(AUTH_MODULE_PATH)
      AUTH_MODULE_DLL_PATTERN: $(AUTH_MODULE_DLL_PATTERN)
      EnableSigning: false

- stage: GenerateRollUpModule
  displayName: 'Generate Roll-Up Module'
  jobs:
  - template: ./generate-beta-rollup-module-template.yml
    parameters:
      Api_Key: $(Api_Key)
      ROLLUP_MODULE_PATH: $(ROLLUP_MODULE_PATH)
      ROLLUP_MODULE_NAME: $(ROLLUP_MODULE_NAME)
      GRAPH_VERSION: $(GRAPH_VERSION)
      BETA_MODULE_PREFIX: $(BETA_MODULE_PREFIX)
      EnableSigning: false
