# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: 'Integrated Pipeline'
variables:
    BRANCH: 'weeklyOpenApiDocsDownload'
    GitUserEmail: 'GraphTooling@service.microsoft.com'
    GitUserName: 'Microsoft Graph DevX Tooling'
    BaseBranch: 'dev'
    MODULE_NAME: 'Authentication'
    MODULE_PATH: 'src\Authentication\Authentication\'
    MODULE_DLL_PATTERN: 'Microsoft.Graph.Authentication.dll'
    MODULE_PREFIX: 'Microsoft.Graph'
    WORKLOAD_MODULE_PATH: 'src\beta\'
    GRAPH_VERSION: 'beta'
    AUTH_MODULE_PATH: 'src\Authentication\Authentication\bin\'
    AUTH_MODULE_DLL_PATTERN: 'Microsoft.Graph.Authentication.dll'
    Api_Key: 'Api_Key'
  
pool:
    vmImage: 'windows-latest'
trigger:
    branches:
      include:
      - master
    paths:
      include:
      - src/Authentication/*

stages:
- stage: DownloadOpenApiDocs
  jobs:
  - job: DownloadOpenAPiDocs
    steps:
    - template: ./download-openapidocs.yml
      parameters:
        GitUserEmail: $(GitUserEmail)
        GitUserName: $(GitUserName)
        BaseBranch: $(BaseBranch)

- stage: GenerateAuthModules
  jobs:
  - template: ./generate-auth-module.yml
    parameters:
      Api_Key: $(Api_Key)
      MODULE_NAME: $(MODULE_NAME)
      MODULE_PATH: $(MODULE_PATH)
      MODULE_DLL_PATTERN: $(MODULE_DLL_PATTERN)

    
- stage: GenerateBetaModules
  jobs:
  - template: ./generate-beta-modules.yml
    parameters:
      Api_Key: $(Api_Key)
      MODULE_PREFIX: $(MODULE_PREFIX)
      WORKLOAD_MODULE_PATH: $(WORKLOAD_MODULE_PATH)
      GRAPH_VERSION: $(GRAPH_VERSION)
      AUTH_MODULE_PATH: $(AUTH_MODULE_PATH)
      AUTH_MODULE_DLL_PATTERN: $(AUTH_MODULE_DLL_PATTERN)

- stage: GenerateRollUpModule
  jobs:
  - template: ./generate-beta-modules.yml
    parameters:
      Api_Key: $(Api_Key)
      MODULE_PATH: $(MODULE_PATH)
      MODULE_NAME: $(MODULE_NAME)
      GRAPH_VERSION: $(GRAPH_VERSION)
